---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.int.glencook.tech
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
