---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-n8n
  namespace: n8n
spec:
  rules:
    - host: n8n.int.glencook.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 80