---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-n8n
  namespace: n8n
spec:
  rules:
    - http:
      host: n8n.int.glencook.tech
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n
            port:
              name: http