---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  releaseName: n8n
  chart:
    spec:
      chart: n8n
      sourceRef:
        kind: HelmRepository
        name: open-8gears
  interval: 24h0m0s
  install:
    remediation:
      retries: 3
  values:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: n8n.int.glencook.tech
    ingress:
      enabled: true
      className: nginx
    database:
      type: postgresdb  # Type of database to use - Other possible types ['sqlite', 'mariadb', 'mysqldb', 'postgresdb'] - default: sqlite
      postgresdb:
        database: n8n      # PostgresDB Database - default: n8n
        host: postgres.int.glencook.tech          # PostgresDB Host - default: localhost
        password: GlenCookTech8090      # PostgresDB Password - default: ''
        port: 5432          # PostgresDB Port - default: 5432
        user:  postgres         # PostgresDB User - default: root
