---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    toolkit.fluxcd.io/tenant: dev-team
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  releaseName: cnpg
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
