---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # Replace the email address with your own contact email
    email: glen@glencook.net
    # The server is replaced in /clusters/production/infrastructure.yaml
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-nginx
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-int
spec:
  acme:
    # Replace the email address with your own contact email
    email: glen@glencook.net
    # The server is replaced in /clusters/production/infrastructure.yaml
    server: https://ca.int.glencook.tech/acme/acme/directory
    privateKeySecretRef:
      name: cai-int-nginx
    solvers:
      - http01:
          ingress:
            class: pomerium
